//HintName: FARunnerMethods.g.cs
namespace Tests
{
    partial class TestSource
    {
        // [LexRule(@"\/\*", Id = 0, Symbol = @"commentBlock")]
        // [LexRule(@"//[^\n]*", Id = 1, Symbol = @"lineComment")]
        // [LexRule(@"[ \t\r\n]+", Id = 2, Symbol = @"whiteSpace")]
        // [LexRule(@"[A-Za-z_][A-Za-z0-9_]*", Id = 3, Symbol = @"identifier")]
        // [LexRule(@"(0|([1-9][0-9]*))((\.[0-9]+[Ee]\-?[1-9][0-9]*)?|\.[0-9]+)", Id = 4, Symbol = @"number")]
        // [LexRule(@"\+", Id = 5, Symbol = @"plus")]
        // [LexRule(@"\-", Id = 6, Symbol = @"minus")]
        // [LexRule(@"\*", Id = 7, Symbol = @"multiply")]
        // [LexRule(@"\/", Id = 8, Symbol = @"divide")]
        // [LexRule(@"%", Id = 9, Symbol = @"modulo")]
        internal static partial FATextReaderDfaTableRunner Calc(System.IO.TextReader text)
        {
            var result = new FATextReaderDfaTableRunner(
                new int[] { -1, 
                    9, 
                    46, 
                    3, 
                    9, 
                    10, 
                    13, 
                    13, 
                    32, 
                    32, 
                    56, 
                    1, 
                    37, 
                    37, 
                    58, 
                    1, 
                    42, 
                    42, 
                    60, 
                    1, 
                    43, 
                    43, 
                    62, 
                    1, 
                    45, 
                    45, 
                    64, 
                    1, 
                    47, 
                    47, 
                    84, 
                    1, 
                    48, 
                    48, 
                    130, 
                    1, 
                    49, 
                    57, 
                    140, 
                    3, 
                    65, 
                    90, 
                    95, 
                    95, 
                    97, 
                    122, 
                    2, 
                    1, 
                    46, 
                    3, 
                    9, 
                    10, 
                    13, 
                    13, 
                    32, 
                    32, 
                    9, 
                    0, 
                    7, 
                    0, 
                    5, 
                    0, 
                    6, 
                    0, 
                    8, 
                    2, 
                    74, 
                    1, 
                    42, 
                    42, 
                    76, 
                    1, 
                    47, 
                    47, 
                    0, 
                    0, 
                    1, 
                    1, 
                    76, 
                    2, 
                    0, 
                    9, 
                    11, 
                    1114111, 
                    4, 
                    1, 
                    90, 
                    1, 
                    46, 
                    46, 
                    -1, 
                    1, 
                    96, 
                    1, 
                    48, 
                    57, 
                    4, 
                    2, 
                    96, 
                    1, 
                    48, 
                    57, 
                    108, 
                    2, 
                    69, 
                    69, 
                    101, 
                    101, 
                    -1, 
                    2, 
                    118, 
                    1, 
                    45, 
                    45, 
                    124, 
                    1, 
                    49, 
                    57, 
                    -1, 
                    1, 
                    124, 
                    1, 
                    49, 
                    57, 
                    4, 
                    1, 
                    124, 
                    1, 
                    48, 
                    57, 
                    4, 
                    2, 
                    90, 
                    1, 
                    46, 
                    46, 
                    130, 
                    1, 
                    48, 
                    57, 
                    3, 
                    1, 
                    140, 
                    4, 
                    48, 
                    57, 
                    65, 
                    90, 
                    95, 
                    95, 
                    97, 
                    122
                                            },
                new int[][] {                     new int[] { -1, 1, 6, 1, 42, 42, 
                        -1, 1, 12, 1, 47, 47, 
                        0, 0
}

                        });
            result.Set(text);
            return result;
        }
    }

}

