//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example {
    using System;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Visual FA", "1.0.0.0")]
    internal sealed partial class ExampleRunner : FAStringRunner {
        private FAMatch _BlockEnd4(ReadOnlySpan<char> s, int cp, int len, int position, int line, int column) {
        q0:
            if ((cp == 42)) {
                this.Advance(s, ref cp, ref len, false);
                goto q1;
            }
            goto errorout;
        q1:
            if ((cp == 47)) {
                this.Advance(s, ref cp, ref len, false);
                goto q2;
            }
            goto errorout;
        q2:
            return FAMatch.Create(4, s.Slice(position, len).ToString(), position, line, column);
        errorout:
            if ((cp == -1)) {
                return FAMatch.Create(-1, s.Slice(position, len).ToString(), position, line, column);
            }
            this.Advance(s, ref cp, ref len, false);
            goto q0;
        }
        private FAMatch NextMatchImpl(ReadOnlySpan<char> s) {
            int ch;
            int len;
            int p;
            int l;
            int c;
            ch = -1;
            len = 0;
            if ((this.position == -1)) {
                this.position = 0;
            }
            p = this.position;
            l = this.line;
            c = this.column;
            this.Advance(s, ref ch, ref len, true);
        q0:
            if ((((ch >= 9) 
                        && (ch <= 13)) 
                        || (ch == 32))) {
                this.Advance(s, ref ch, ref len, false);
                goto q1;
            }
            if ((ch == 45)) {
                this.Advance(s, ref ch, ref len, false);
                goto q2;
            }
            if ((ch == 47)) {
                this.Advance(s, ref ch, ref len, false);
                goto q5;
            }
            if ((ch == 48)) {
                this.Advance(s, ref ch, ref len, false);
                goto q9;
            }
            if (((ch >= 49) 
                        && (ch <= 57))) {
                this.Advance(s, ref ch, ref len, false);
                goto q3;
            }
            if (((((ch >= 65) 
                        && (ch <= 90)) 
                        || (ch == 95)) 
                        || ((ch >= 97) 
                        && (ch <= 122)))) {
                this.Advance(s, ref ch, ref len, false);
                goto q10;
            }
            goto errorout;
        q1:
            return FAMatch.Create(2, s.Slice(p, len).ToString(), p, l, c);
        q2:
            if (((ch >= 49) 
                        && (ch <= 57))) {
                this.Advance(s, ref ch, ref len, false);
                goto q3;
            }
            goto errorout;
        q3:
            if (((ch >= 48) 
                        && (ch <= 57))) {
                this.Advance(s, ref ch, ref len, false);
                goto q4;
            }
            return FAMatch.Create(1, s.Slice(p, len).ToString(), p, l, c);
        q4:
            if (((ch >= 48) 
                        && (ch <= 57))) {
                this.Advance(s, ref ch, ref len, false);
                goto q4;
            }
            return FAMatch.Create(1, s.Slice(p, len).ToString(), p, l, c);
        q5:
            if ((ch == 42)) {
                this.Advance(s, ref ch, ref len, false);
                goto q6;
            }
            if ((ch == 47)) {
                this.Advance(s, ref ch, ref len, false);
                goto q7;
            }
            goto errorout;
        q6:
            return _BlockEnd4(s, ch, len, p, l, c);
        q7:
            if ((((ch >= 0) 
                        && (ch <= 9)) 
                        || ((ch >= 11) 
                        && (ch <= 1114111)))) {
                this.Advance(s, ref ch, ref len, false);
                goto q8;
            }
            return FAMatch.Create(3, s.Slice(p, len).ToString(), p, l, c);
        q8:
            if ((((ch >= 0) 
                        && (ch <= 9)) 
                        || ((ch >= 11) 
                        && (ch <= 1114111)))) {
                this.Advance(s, ref ch, ref len, false);
                goto q8;
            }
            return FAMatch.Create(3, s.Slice(p, len).ToString(), p, l, c);
        q9:
            return FAMatch.Create(1, s.Slice(p, len).ToString(), p, l, c);
        q10:
            if ((((((ch >= 48) 
                        && (ch <= 57)) 
                        || ((ch >= 65) 
                        && (ch <= 90))) 
                        || (ch == 95)) 
                        || ((ch >= 97) 
                        && (ch <= 122)))) {
                this.Advance(s, ref ch, ref len, false);
                goto q11;
            }
            return FAMatch.Create(0, s.Slice(p, len).ToString(), p, l, c);
        q11:
            if ((((((ch >= 48) 
                        && (ch <= 57)) 
                        || ((ch >= 65) 
                        && (ch <= 90))) 
                        || (ch == 95)) 
                        || ((ch >= 97) 
                        && (ch <= 122)))) {
                this.Advance(s, ref ch, ref len, false);
                goto q11;
            }
            return FAMatch.Create(0, s.Slice(p, len).ToString(), p, l, c);
        errorout:
            if (((((((((((ch == -1) 
                        || ((ch >= 9) 
                        && (ch <= 13))) 
                        || (ch == 32)) 
                        || (ch == 45)) 
                        || (ch == 47)) 
                        || (ch == 48)) 
                        || ((ch >= 49) 
                        && (ch <= 57))) 
                        || ((ch >= 65) 
                        && (ch <= 90))) 
                        || (ch == 95)) 
                        || ((ch >= 97) 
                        && (ch <= 122)))) {
                if ((len == 0)) {
                    return FAMatch.Create(-2, null, 0, 0, 0);
                }
                return FAMatch.Create(-1, s.Slice(p, len).ToString(), p, l, c);
            }
            this.Advance(s, ref ch, ref len, false);
            goto errorout;
        }
        public override FAMatch NextMatch() {
            return this.NextMatchImpl(this.@string);
        }
    }
}
