object = "{"
object_end = "}"
array = "["
array_end = "]"
field = ":"
comma = ","
number = '-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?'
boolean = 'true|false'
null = "null"
_string = '"([^\n"\\]|\\([btrnf"\\/]|(u[0-9A-Fa-f]{4})))*"'
white_space = '[ \t\r\n]+'